[package]
name = "stellars-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
libstellars = {path = "../libstellars"}
eframe = {version =  "0.33.3", default-features = false, features = ["accesskit", "glow", "wayland", "x11"]}
image = "0.25.9"
rfd = "0.17.2"
cpal = "0.17.1"