[package]
name = "libstellars"
version = "0.1.0"
edition = "2024"

[features]
test-utils = ["dep:serde_json", "dep:paste"]

[dependencies]
serde_json = { version = "1.0.149", optional = true }
paste = { version = "1.0.15", optional = true }